### ISSUE TITLE
Design & Implement Overture Backend for IOBIO Integration

### ISSUE THREAD

**Issue by b-f-chan** [overture-stack/iobio-components#26]
Design & implement the Overture backend for IOBIO integration

- [ ] Research IOBIO server and develop technical design for the Overture integration
    - [ ] Research Overture components (e.g. Elastic, Song, Score, etc) to determine their needs to support the IOBIO server
- [ ] Initialize and configure local instance of IOBIO Server on Overture
- [ ] Integrate Stage with IOBIO server based on decision on technical design
    - [ ] Make our own package for the local IOBIO server
